#!/usr/bin/env python
import cluster_storage
import sys
import os

if len(sys.argv) > 1:
    dir = sys.argv[1]
else:
    dir = ""

if dir.startswith('grid:/'):
    dir = dir[6:]
if not dir.startswith('/'):
    dir = os.path.join(os.environ['LFC_HOME'], dir)        

cs = cluster_storage.ClusterStorageEngine()
l =  cs.list_dir(dir)
for e in l:
    print e

